import {auth,db,$,show,esc,onAuthStateChanged,signOut,collection,getDocs,doc,getDoc,setDoc,updateDoc,serverTimestamp} from './app.js?v=20260730-question-editor-v12';
let currentExam=null,currentQuestions=[],filteredQuestions=[];
const norm=v=>String(v||'').trim();
const upper=v=>norm(v).toUpperCase();
const examPublicId=e=>e?.examId||e?.examCode||e?.id||'';
const prettyDate=v=>{if(!v)return '-';const d=v?.toDate?v.toDate():new Date(v);return isNaN(d)?String(v):d.toLocaleString('en-IN');};
const deepQuestion=(q,i)=>({id:q?.id||`q-${i+1}`,subject:q?.subject||'General',question:q?.question||q?.text||'',options:Array.isArray(q?.options)?q.options.map((o,j)=>typeof o==='string'?{key:['A','B','C','D'][j],text:o}:{key:o.key||['A','B','C','D'][j],text:o.text||o.value||''}):['A','B','C','D'].map(k=>({key:k,text:''})),answer:String(q?.answer||q?.correctAnswer||'A').toUpperCase()});
onAuthStateChanged(auth,u=>{if(!u)location.href='login.html';});
$('logout').onclick=async()=>{await signOut(auth);location.href='login.html';};
async function findExam(id){const key=upper(id);if(!key)return null;const direct=await getDoc(doc(db,'exams',key));if(direct.exists())return{id:direct.id,...direct.data()};const snap=await getDocs(collection(db,'exams'));let found=null;snap.forEach(d=>{const x=d.data();if(!found&&[d.id,x.examId,x.examCode,x.title].some(v=>upper(v)===key))found={id:d.id,...x};});return found;}
async function loadExam(exam){try{currentExam=exam;const candidates=[examPublicId(exam),exam.id].filter(Boolean);let qdoc=null;for(const id of [...new Set(candidates)]){const s=await getDoc(doc(db,'examQuestions',id));if(s.exists()){qdoc={id:s.id,...s.data()};break;}}if(!qdoc)throw new Error('ఈ exam questions document దొరకలేదు.');currentQuestions=(qdoc.questions||[]).map(deepQuestion);filteredQuestions=[...currentQuestions];currentExam.questionDocId=qdoc.id;$('examEditorSection').hidden=false;$('allExamsSection').hidden=true;$('loadedExamTitle').textContent=exam.title||exam.examId||exam.id;$('loadedExamMeta').textContent=`Exam ID: ${examPublicId(exam)} • ${exam.instituteName||'-'} • ${exam.batchName||'-'} • ${currentQuestions.length} Questions`;$('questionSearchInput').value='';renderQuestions();$('examEditorSection').scrollIntoView({behavior:'smooth',block:'start'});show(`${currentQuestions.length} questions loaded ✅`);}catch(e){show(e.message,'err');}}
function renderQuestions(){const box=$('questionsList');$('questionSummary').innerHTML=`<b>${filteredQuestions.length}</b> of <b>${currentQuestions.length}</b> questions`;if(!filteredQuestions.length){box.innerHTML='<div class="msg warn">Matching question dorakaledu.</div>';return;}box.innerHTML=filteredQuestions.map(q=>{const actual=currentQuestions.indexOf(q),opts=q.options||[];return `<article class="qeQuestionCard" id="qe-q-${actual+1}"><div class="qeQuestionHead"><div><b>Q${actual+1}</b><span>${esc(q.subject||'General')}</span></div><button class="qeEditBtn" data-edit="${actual}">Edit</button></div><div class="qeQuestionView">${esc(q.question).replace(/\n/g,'<br>')}</div><div class="qeOptionPreview">${opts.map(o=>`<div class="${q.answer===o.key?'correct':''}"><b>${esc(o.key)}</b><span>${esc(o.text)}</span></div>`).join('')}</div><div class="qeEditForm" data-form="${actual}" hidden><label>Subject<input data-field="subject" value="${esc(q.subject)}"></label><label>Question<textarea data-field="question" rows="6">${esc(q.question)}</textarea></label>${opts.map((o,j)=>`<label>Option ${o.key}<textarea data-option="${j}" rows="2">${esc(o.text)}</textarea></label>`).join('')}<label>Correct Answer<select data-field="answer">${['A','B','C','D'].map(k=>`<option ${q.answer===k?'selected':''}>${k}</option>`).join('')}</select></label><div class="qeFormActions"><button class="green" data-save="${actual}">Save Question</button><button class="gray" data-cancel="${actual}">Cancel</button></div></div></article>`}).join('');bindQuestionButtons();}
function bindQuestionButtons(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const i=+b.dataset.edit;document.querySelector(`[data-form="${i}"]`).hidden=false;b.hidden=true;document.getElementById(`qe-q-${i+1}`).scrollIntoView({behavior:'smooth',block:'start'});});document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>renderQuestions());document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveQuestion(+b.dataset.save,b));}
async function saveQuestion(index,btn){try{const card=document.getElementById(`qe-q-${index+1}`),q=currentQuestions[index];q.subject=norm(card.querySelector('[data-field="subject"]').value)||'General';q.question=norm(card.querySelector('[data-field="question"]').value);card.querySelectorAll('[data-option]').forEach(el=>q.options[+el.dataset.option].text=norm(el.value));q.answer=card.querySelector('[data-field="answer"]').value;if(!q.question)throw new Error('Question empty ga undakudadhu.');if(q.options.some(o=>!norm(o.text)))throw new Error('A, B, C, D options అన్నీ fill చేయండి.');btn.disabled=true;btn.textContent='Saving...';await setDoc(doc(db,'examQuestions',currentExam.questionDocId),{examId:examPublicId(currentExam),questions:currentQuestions,questionCount:currentQuestions.length,subjectSummary:subjectSummary(),updatedAt:serverTimestamp()},{merge:true});await updateDoc(doc(db,'exams',currentExam.id),{questionCount:currentQuestions.length,subjectCount:subjectSummary().length,subjectSummary:subjectSummary(),updatedAt:serverTimestamp()});applyQuestionSearch();show(`Question ${index+1} saved successfully ✅`);}catch(e){show(e.message,'err');btn.disabled=false;btn.textContent='Save Question';}}
function subjectSummary(){return [...new Set(currentQuestions.map(q=>q.subject||'General'))].map(subject=>({subject,total:currentQuestions.filter(q=>(q.subject||'General')===subject).length}));}
function applyQuestionSearch(){const raw=norm($('questionSearchInput').value);if(!raw){filteredQuestions=[...currentQuestions];renderQuestions();return;}const n=Number(raw);if(Number.isInteger(n)&&n>0){filteredQuestions=currentQuestions[n-1]?[currentQuestions[n-1]]:[];}else{const key=raw.toLocaleLowerCase();filteredQuestions=currentQuestions.filter(q=>`${q.question} ${q.subject} ${(q.options||[]).map(o=>o.text).join(' ')}`.toLocaleLowerCase().includes(key));}renderQuestions();if(filteredQuestions.length===1){const i=currentQuestions.indexOf(filteredQuestions[0]);setTimeout(()=>document.getElementById(`qe-q-${i+1}`)?.scrollIntoView({behavior:'smooth',block:'start'}),50);}}
$('searchExamBtn').onclick=async()=>{try{const id=$('examSearchInput').value;if(!norm(id))throw new Error('Exam ID enter చేయండి.');$('searchExamBtn').disabled=true;$('searchExamBtn').textContent='Searching...';const exam=await findExam(id);if(!exam)throw new Error('Exam dorakaledu.');await loadExam(exam);}catch(e){show(e.message,'err');}finally{$('searchExamBtn').disabled=false;$('searchExamBtn').textContent='Search Exam';}};
$('allExamsBtn').onclick=async()=>{try{$('allExamsBtn').disabled=true;$('allExamsBtn').textContent='Loading...';const snap=await getDocs(collection(db,'exams'));const rows=[];snap.forEach(d=>rows.push({id:d.id,...d.data()}));rows.sort((a,b)=>String(b.createdAt?.seconds||b.startTime||'').localeCompare(String(a.createdAt?.seconds||a.startTime||'')));$('allExamsSection').hidden=false;$('examEditorSection').hidden=true;$('allExamsCount').textContent=`${rows.length} exams`;$('allExamsList').innerHTML=rows.length?rows.map((e,i)=>`<button class="qeExamRow" data-exam-index="${i}"><span><b>${esc(e.title||e.examId||e.id)}</b><small>${esc(e.instituteName||'-')} • ${esc(e.batchName||'-')} • ${Number(e.questionCount||0)} Questions</small></span><em>${esc(e.status||'active')}</em></button>`).join(''):'<div class="msg warn">No exams found.</div>';document.querySelectorAll('[data-exam-index]').forEach(b=>b.onclick=()=>loadExam(rows[+b.dataset.examIndex]));$('allExamsSection').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){show(e.message,'err');}finally{$('allExamsBtn').disabled=false;$('allExamsBtn').textContent='All Exams';}};
$('closeAllExams').onclick=()=>{$('allExamsSection').hidden=true;};$('searchQuestionBtn').onclick=applyQuestionSearch;$('clearQuestionSearch').onclick=()=>{$('questionSearchInput').value='';applyQuestionSearch();};$('questionSearchInput').addEventListener('keydown',e=>{if(e.key==='Enter')applyQuestionSearch();});$('reloadExamBtn').onclick=()=>currentExam&&loadExam(currentExam);
